### ISSUE TITLE
Create Work Project Checklist 1

### ISSUE THREAD

**Issue by JavascriptLearner815** [JavascriptLearner815/new-chessik-site#2]
- [ ] Start Language Lessons

- [ ] Make First Lesson

- [ ] Make First Lesson's Worksheet

- [ ] Make Next Lesson

- [ ] Start Math Lessons

- [ ] Start History Lessons

- [ ] Start Science Lessons
